cloud:
  aws:
    credentials:
      access-key: AKIAQRASRCD4NAEZCHU5 # Replace with your actual access key
      secret-key: /3IuOy2EWlwtKmVcUvg6QlIGLjAvfuuaajxb9cI2 # Replace with your actual secret key
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: smart-plant

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
