cloud:
  aws:
    credentials:
      access-key: AKIAQRASRCD4NAEZCHU5
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: smart-plant

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
